version: '3.8'

services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8978:8978"
    environment:
      - DBC_SERVER_PORT=8978
    volumes:
      - dbeaver-data:/workspace
    restart: unless-stopped

  database:
    image: postgres:16.0-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  dbeaver-data:
